%% Search for a specified operating point for the model - SixDOF_Equationgs_of_Motion.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 9.4 and Simulink Control Design (TM) 5.1.
%
% Generated on: 08-Dec-2020 23:47:27

%% Specify the model name
model = 'SixDOF_Equationgs_of_Motion';

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - SixDOF_Equationgs_of_Motion/6DOF (Euler Angles)/Calculate DCM & Euler Angles/phi theta psi
% - Default model initial conditions are used to initialize optimization.

% State (2) - SixDOF_Equationgs_of_Motion/6DOF (Euler Angles)/p,q,r
% - Default model initial conditions are used to initialize optimization.

% State (3) - SixDOF_Equationgs_of_Motion/6DOF (Euler Angles)/ub,vb,wb
% - Default model initial conditions are used to initialize optimization.

% State (4) - SixDOF_Equationgs_of_Motion/6DOF (Euler Angles)/xe,ye,ze
% - Default model initial conditions are used to initialize optimization.

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - SixDOF_Equationgs_of_Motion/Alpha
opspec.Inputs(1).u = 0.9862;

% Input (2) - SixDOF_Equationgs_of_Motion/delta_e
opspec.Inputs(2).u = -2.6627;

% Input (3) - SixDOF_Equationgs_of_Motion/T
opspec.Inputs(3).u = 31.6826;
opspec.Inputs(3).Min = 0;

% Input (4) - SixDOF_Equationgs_of_Motion/h
opspec.Inputs(4).u = 5000;
opspec.Inputs(4).Known = true;

% Input (5) - SixDOF_Equationgs_of_Motion/V
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(5).Known = [true;false;false];

% Input (6) - SixDOF_Equationgs_of_Motion/Beta
opspec.Inputs(6).u = 2.2204e-16;
opspec.Inputs(6).Known = true;

% Input (7) - SixDOF_Equationgs_of_Motion/delta_r
opspec.Inputs(7).u = 2.2204e-16;

% Input (8) - SixDOF_Equationgs_of_Motion/delta_a
opspec.Inputs(8).u = 2.2204e-16;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - SixDOF_Equationgs_of_Motion/Vx_out
% - Default model initial conditions are used to initialize optimization.

% Output (2) - SixDOF_Equationgs_of_Motion/Vy_out
% - Default model initial conditions are used to initialize optimization.

% Output (3) - SixDOF_Equationgs_of_Motion/Vz_out
% - Default model initial conditions are used to initialize optimization.

% Output (4) - SixDOF_Equationgs_of_Motion/h_out
% - Default model initial conditions are used to initialize optimization.

% Output (5) - SixDOF_Equationgs_of_Motion/Vbx_out
% - Default model initial conditions are used to initialize optimization.

% Output (6) - SixDOF_Equationgs_of_Motion/Vby_out
% - Default model initial conditions are used to initialize optimization.

% Output (7) - SixDOF_Equationgs_of_Motion/Vbz_out
% - Default model initial conditions are used to initialize optimization.

% Output (8) - SixDOF_Equationgs_of_Motion/pbar_out
% - Default model initial conditions are used to initialize optimization.

% Output (9) - SixDOF_Equationgs_of_Motion/qbar_out
% - Default model initial conditions are used to initialize optimization.

% Output (10) - SixDOF_Equationgs_of_Motion/rbar_out
% - Default model initial conditions are used to initialize optimization.

% Output (11) - SixDOF_Equationgs_of_Motion/phi_out
% - Default model initial conditions are used to initialize optimization.

% Output (12) - SixDOF_Equationgs_of_Motion/theta_out
% - Default model initial conditions are used to initialize optimization.

% Output (13) - SixDOF_Equationgs_of_Motion/psi_out
% - Default model initial conditions are used to initialize optimization.

% Output (14) - SixDOF_Equationgs_of_Motion/DCM_out
% - Default model initial conditions are used to initialize optimization.

% Output (15) - SixDOF_Equationgs_of_Motion/alphadot_out
% - Default model initial conditions are used to initialize optimization.


%% Create the options
opt = findopOptions('DisplayReport','iter');

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);